attention_resolutions:
- 16
- 8
batch_size: 32
beta_end: 0.02
beta_schedule: linear
beta_start: 0.0001
channel_mult:
- 1
- 2
- 4
- 8
checkpoint_dir: outputs/checkpoints/diffusion_128
checkpoint_interval: 5000
data_root: data/processed_cats_128
device: mps
dropout: 0.1
ema_decay: 0.9999
gradient_accumulation_steps: 1
image_size: 128
in_channels: 3
learning_rate: 0.0002
log_dir: outputs/logs/diffusion
log_interval: 100
mixed_precision: true
model_channels: 128
model_type: ddpm
num_epochs: 1000
early_stopping_patience: 2
num_heads: 8
num_res_blocks: 2
num_samples: 16
num_timesteps: 1000
num_workers: 4
out_channels: 3
pin_memory: true
sample_dir: outputs/generated_samples/diffusion_128
sample_interval: 1000
use_scale_shift_norm: true
