ada_length: 500000
ada_target: 0.6
augment_p: 0.0
batch_size: 16
channel_multiplier: 2
checkpoint_dir: outputs/checkpoints/gan_128
checkpoint_interval: 5000
d_channels:
- 32
- 64
- 128
- 256
- 512
- 512
- 512
- 512
d_lr: 0.002
d_reg_interval: 16
data_root: data/processed_cats_128
device: mps
g_channels:
- 512
- 512
- 512
- 512
- 256
- 128
- 64
- 32
g_lr: 0.002
g_reg_interval: 4
image_size: 128
latent_dim: 512
log_dir: outputs/logs/gan
log_interval: 100
mbstd_group_size: 4
model_type: stylegan2
n_layers: 8
n_mlp: 8
num_epochs: 1000
early_stopping_patience: 2
num_samples: 16
num_workers: 4
pin_memory: true
pl_weight: 2.0
r1_gamma: 10.0
sample_dir: outputs/generated_samples/gan_128
sample_interval: 1000
style_dim: 512
